const BookActionTypes = {
  GET_BEST_SELLING_BOOKS_REQUESTED: 'GET_BEST_SELLING_BOOKS_REQUESTED',
  GET_BEST_SELLING_BOOKS_FINISHED: 'GET_BEST_SELLING_BOOKS_FINISHED',
}

export default BookActionTypes
